-- local opt = vim.opt
--
-- opt.cursorline = true --光标提示线
-- opt.clipboard:append "unnamedplus" --剪贴板
--
-- opt.termguicolors = true
--
-- opt.wrap = false
-- opt.foldcolumn = "0"
-- opt.signcolumn = "yes"
--
-- opt.splitright = true
-- opt.splitbelow = true
--
-- require("telescope").load_extension "yank_history"
-- require("telescope").load_extension "catppuccin" --telescope->yanky,catppuccin联动

-- local configs = require 'lspconfig.configs'
--
-- configs.ast_grep = {
--   default_config = {
--     cmd = {'ast-grep', 'lsp'};
--     single_file_support = false;
--     root_dir = nvim_lsp.util.root_pattern('sgconfig.yml');
--   };
-- }
--
